---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfplatformrecovery/backup-and-restore-minimal}

inputs:
- name: disaster-recovery-acceptance-tests
  path: src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests

run:
  path: src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/ci/tasks/unit-tests/task.sh

params:
  GITHUB_SSH_KEY:
